[package]
name = "zig_plugin"
version = "0.2.1"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "1.0.0"
proto_pdk = "0.14.2"
serde = "1.0.195"

[dev-dependencies]
proto_pdk_test_utils = "0.16.1"
starbase_sandbox = "0.1.12"
tokio = { version = "1.35.1", features = ["full"] }

[features]
default = ["wasm"]
wasm = []

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
