[package]
name = "zig_plugin"
version = "0.5.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "1.1.0"
proto_pdk = "0.18.0"
serde = "1.0.200"

[dev-dependencies]
proto_pdk_test_utils = "0.22.0"
starbase_sandbox = "0.6.0"
tokio = { version = "1.37.0", features = ["full"] }

[features]
default = ["wasm"]
wasm = []

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
