[package]
name = "zig_plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.4"
proto_pdk = "0.12.2"
serde = "1.0.194"

[dev-dependencies]
proto_pdk_test_utils = "0.14.5"
starbase_sandbox = "0.1.12"
tokio = "1.35.1"

[features]
default = ["wasm"]
wasm = []

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"
